package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name="tb_activity")
public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.id
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.active
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.owner
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Long owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.name
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.start
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.end
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.state
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.type
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.comment
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.expected_income
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Double expectedIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.realized_income
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Double realizedIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.expect_people
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Integer expectPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.realized_people
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private String realizedPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.expect_cost
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Long expectCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.realized_cost
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Long realizedCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.create_uid
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.write_uid
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.create_date
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity.write_date
     *
     * @mbggenerated Tue Apr 25 20:46:02 CST 2017
     */
	@Column
    private Date writeDate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Long getOwner() {
		return owner;
	}

	public void setOwner(Long owner) {
		this.owner = owner;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStart() {
		return start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Double getExpectedIncome() {
		return expectedIncome;
	}

	public void setExpectedIncome(Double expectedIncome) {
		this.expectedIncome = expectedIncome;
	}

	public Double getRealizedIncome() {
		return realizedIncome;
	}

	public void setRealizedIncome(Double realizedIncome) {
		this.realizedIncome = realizedIncome;
	}

	public Integer getExpectPeople() {
		return expectPeople;
	}

	public void setExpectPeople(Integer expectPeople) {
		this.expectPeople = expectPeople;
	}

	public String getRealizedPeople() {
		return realizedPeople;
	}

	public void setRealizedPeople(String realizedPeople) {
		this.realizedPeople = realizedPeople;
	}

	public Long getExpectCost() {
		return expectCost;
	}

	public void setExpectCost(Long expectCost) {
		this.expectCost = expectCost;
	}

	public Long getRealizedCost() {
		return realizedCost;
	}

	public void setRealizedCost(Long realizedCost) {
		this.realizedCost = realizedCost;
	}

	public Long getCreateUid() {
		return createUid;
	}

	public void setCreateUid(Long createUid) {
		this.createUid = createUid;
	}

	public Long getWriteUid() {
		return writeUid;
	}

	public void setWriteUid(Long writeUid) {
		this.writeUid = writeUid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getWriteDate() {
		return writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Override
	public String toString() {
		return "Activity [id=" + id + ", active=" + active + ", owner=" + owner + ", name=" + name + ", start=" + start
				+ ", end=" + end + ", state=" + state + ", type=" + type + ", comment=" + comment + ", expectedIncome="
				+ expectedIncome + ", realizedIncome=" + realizedIncome + ", expectPeople=" + expectPeople
				+ ", realizedPeople=" + realizedPeople + ", expectCost=" + expectCost + ", realizedCost=" + realizedCost
				+ ", createUid=" + createUid + ", writeUid=" + writeUid + ", createDate=" + createDate + ", writeDate="
				+ writeDate + "]";
	}

}