package com.radacat.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_agency")
public class Agency implements Serializable{
    
	/**
	 * serialVersionUID
	 * long
	 */
	private static final long serialVersionUID = -4057734118044592144L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.picking_count
     * 
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	//提货数量
	@Column
    private Double pickingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.picking_price
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	//提货单价
	@Column
    private Double pickingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.picking_total
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	//提货总价
	@Column
    private Integer pickingTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.product_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	//商品编号
	@Column
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.discount
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	//折扣
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.register_count
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    //当地注册人数
    private Integer registerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.area_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    //地区编号
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_agency.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Date writeDate;

    public Agency() {
	}

	public Agency(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Double getPickingCount() {
		return pickingCount;
	}

	public void setPickingCount(Double pickingCount) {
		this.pickingCount = pickingCount;
	}

	public Double getPickingPrice() {
		return pickingPrice;
	}

	public void setPickingPrice(Double pickingPrice) {
		this.pickingPrice = pickingPrice;
	}

	public Integer getPickingTotal() {
		return pickingTotal;
	}

	public void setPickingTotal(Integer pickingTotal) {
		this.pickingTotal = pickingTotal;
	}

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Double getDiscount() {
		return discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public Integer getRegisterCount() {
		return registerCount;
	}

	public void setRegisterCount(Integer registerCount) {
		this.registerCount = registerCount;
	}

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public Long getCreateUid() {
		return createUid;
	}

	public void setCreateUid(Long createUid) {
		this.createUid = createUid;
	}

	public Long getWriteUid() {
		return writeUid;
	}

	public void setWriteUid(Long writeUid) {
		this.writeUid = writeUid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getWriteDate() {
		return writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	@Override
	public String toString() {
		return "Agency [id=" + id + ", active=" + active + ", pickingCount=" + pickingCount + ", pickingPrice="
				+ pickingPrice + ", pickingTotal=" + pickingTotal + ", productId=" + productId + ", discount="
				+ discount + ", registerCount=" + registerCount + ", areaId=" + areaId + ", createUid=" + createUid
				+ ", writeUid=" + writeUid + ", createDate=" + createDate + ", writeDate=" + writeDate + "]";
	}
}