package com.radacat.domain;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_country.id
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_country.code
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_country.name
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_country.id
     *
     * @return the value of tb_country.id
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_country.id
     *
     * @param id the value for tb_country.id
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_country.code
     *
     * @return the value of tb_country.code
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_country.code
     *
     * @param code the value for tb_country.code
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_country.name
     *
     * @return the value of tb_country.name
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_country.name
     *
     * @param name the value for tb_country.name
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}