package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name="tb_depart")
public class Depart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.director_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long directorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.parent_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
	private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Integer createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Integer writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depart.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.id
     *
     * @return the value of tb_depart.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.id
     *
     * @param id the value for tb_depart.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.active
     *
     * @return the value of tb_depart.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.active
     *
     * @param active the value for tb_depart.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.name
     *
     * @return the value of tb_depart.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.name
     *
     * @param name the value for tb_depart.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.company_id
     *
     * @return the value of tb_depart.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.company_id
     *
     * @param companyId the value for tb_depart.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.director_id
     *
     * @return the value of tb_depart.director_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.director_id
     *
     * @param directorId the value for tb_depart.director_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setDirectorId(Long directorId) {
        this.directorId = directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.parent_id
     *
     * @return the value of tb_depart.parent_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.parent_id
     *
     * @param parentId the value for tb_depart.parent_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.create_uid
     *
     * @return the value of tb_depart.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.create_uid
     *
     * @param createUid the value for tb_depart.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.write_uid
     *
     * @return the value of tb_depart.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.write_uid
     *
     * @param writeUid the value for tb_depart.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.create_date
     *
     * @return the value of tb_depart.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.create_date
     *
     * @param createDate the value for tb_depart.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depart.write_date
     *
     * @return the value of tb_depart.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depart.write_date
     *
     * @param writeDate the value for tb_depart.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
}