package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_goal")
public class Goal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.type
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.owner_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
	private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_total
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month1
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month2
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month3
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month4
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month5
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month6
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month7
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month8
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month9
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month10
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month11
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth11;

    /**
     * This field 8was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.goal_month12
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double goalMonth12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month1
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month2
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month3
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month4
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month5
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month6
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month7
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month8
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month9
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month10
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month11
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_month12
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeMonth12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.complete_total
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Double completeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goal.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	public Double getGoalTotal() {
		return goalTotal;
	}

	public void setGoalTotal(Double goalTotal) {
		this.goalTotal = goalTotal;
	}

	public Double getGoalMonth1() {
		return goalMonth1;
	}

	public void setGoalMonth1(Double goalMonth1) {
		this.goalMonth1 = goalMonth1;
	}

	public Double getGoalMonth2() {
		return goalMonth2;
	}

	public void setGoalMonth2(Double goalMonth2) {
		this.goalMonth2 = goalMonth2;
	}

	public Double getGoalMonth3() {
		return goalMonth3;
	}

	public void setGoalMonth3(Double goalMonth3) {
		this.goalMonth3 = goalMonth3;
	}

	public Double getGoalMonth4() {
		return goalMonth4;
	}

	public void setGoalMonth4(Double goalMonth4) {
		this.goalMonth4 = goalMonth4;
	}

	public Double getGoalMonth5() {
		return goalMonth5;
	}

	public void setGoalMonth5(Double goalMonth5) {
		this.goalMonth5 = goalMonth5;
	}

	public Double getGoalMonth6() {
		return goalMonth6;
	}

	public void setGoalMonth6(Double goalMonth6) {
		this.goalMonth6 = goalMonth6;
	}

	public Double getGoalMonth7() {
		return goalMonth7;
	}

	public void setGoalMonth7(Double goalMonth7) {
		this.goalMonth7 = goalMonth7;
	}

	public Double getGoalMonth8() {
		return goalMonth8;
	}

	public void setGoalMonth8(Double goalMonth8) {
		this.goalMonth8 = goalMonth8;
	}

	public Double getGoalMonth9() {
		return goalMonth9;
	}

	public void setGoalMonth9(Double goalMonth9) {
		this.goalMonth9 = goalMonth9;
	}

	public Double getGoalMonth10() {
		return goalMonth10;
	}

	public void setGoalMonth10(Double goalMonth10) {
		this.goalMonth10 = goalMonth10;
	}

	public Double getGoalMonth11() {
		return goalMonth11;
	}

	public void setGoalMonth11(Double goalMonth11) {
		this.goalMonth11 = goalMonth11;
	}

	public Double getGoalMonth12() {
		return goalMonth12;
	}

	public void setGoalMonth12(Double goalMonth12) {
		this.goalMonth12 = goalMonth12;
	}

	public Double getCompleteMonth1() {
		return completeMonth1;
	}

	public void setCompleteMonth1(Double completeMonth1) {
		this.completeMonth1 = completeMonth1;
	}

	public Double getCompleteMonth2() {
		return completeMonth2;
	}

	public void setCompleteMonth2(Double completeMonth2) {
		this.completeMonth2 = completeMonth2;
	}

	public Double getCompleteMonth3() {
		return completeMonth3;
	}

	public void setCompleteMonth3(Double completeMonth3) {
		this.completeMonth3 = completeMonth3;
	}

	public Double getCompleteMonth4() {
		return completeMonth4;
	}

	public void setCompleteMonth4(Double completeMonth4) {
		this.completeMonth4 = completeMonth4;
	}

	public Double getCompleteMonth5() {
		return completeMonth5;
	}

	public void setCompleteMonth5(Double completeMonth5) {
		this.completeMonth5 = completeMonth5;
	}

	public Double getCompleteMonth6() {
		return completeMonth6;
	}

	public void setCompleteMonth6(Double completeMonth6) {
		this.completeMonth6 = completeMonth6;
	}

	public Double getCompleteMonth7() {
		return completeMonth7;
	}

	public void setCompleteMonth7(Double completeMonth7) {
		this.completeMonth7 = completeMonth7;
	}

	public Double getCompleteMonth8() {
		return completeMonth8;
	}

	public void setCompleteMonth8(Double completeMonth8) {
		this.completeMonth8 = completeMonth8;
	}

	public Double getCompleteMonth9() {
		return completeMonth9;
	}

	public void setCompleteMonth9(Double completeMonth9) {
		this.completeMonth9 = completeMonth9;
	}

	public Double getCompleteMonth10() {
		return completeMonth10;
	}

	public void setCompleteMonth10(Double completeMonth10) {
		this.completeMonth10 = completeMonth10;
	}

	public Double getCompleteMonth11() {
		return completeMonth11;
	}

	public void setCompleteMonth11(Double completeMonth11) {
		this.completeMonth11 = completeMonth11;
	}

	public Double getCompleteMonth12() {
		return completeMonth12;
	}

	public void setCompleteMonth12(Double completeMonth12) {
		this.completeMonth12 = completeMonth12;
	}

	public Double getCompleteTotal() {
		return completeTotal;
	}

	public void setCompleteTotal(Double completeTotal) {
		this.completeTotal = completeTotal;
	}

	public Long getCreateUid() {
		return createUid;
	}

	public void setCreateUid(Long createUid) {
		this.createUid = createUid;
	}

	public Long getWriteUid() {
		return writeUid;
	}

	public void setWriteUid(Long writeUid) {
		this.writeUid = writeUid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getWriteDate() {
		return writeDate;
	}

	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}
}