package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_history_point")
public class HistoryPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.points_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
	private Integer pointsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.owner_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.crate_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long crateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_point.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.id
     *
     * @return the value of tb_history_point.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.id
     *
     * @param id the value for tb_history_point.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.active
     *
     * @return the value of tb_history_point.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.active
     *
     * @param active the value for tb_history_point.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.points_id
     *
     * @return the value of tb_history_point.points_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getPointsId() {
        return pointsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.points_id
     *
     * @param pointsId the value for tb_history_point.points_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setPointsId(Integer pointsId) {
        this.pointsId = pointsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.owner_id
     *
     * @return the value of tb_history_point.owner_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.owner_id
     *
     * @param ownerId the value for tb_history_point.owner_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.crate_uid
     *
     * @return the value of tb_history_point.crate_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCrateUid() {
        return crateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.crate_uid
     *
     * @param crateUid the value for tb_history_point.crate_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCrateUid(Long crateUid) {
        this.crateUid = crateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.write_uid
     *
     * @return the value of tb_history_point.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.write_uid
     *
     * @param writeUid the value for tb_history_point.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteUid(Long writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.create_date
     *
     * @return the value of tb_history_point.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.create_date
     *
     * @param createDate the value for tb_history_point.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_point.write_date
     *
     * @return the value of tb_history_point.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_point.write_date
     *
     * @param writeDate the value for tb_history_point.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
}