package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name="tb_partner")
public class Partner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.type
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
	private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
	private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.gender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.hometown
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String hometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.trade_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.function
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String function;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.birthday
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.signature
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.email
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.mobile
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.phone
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.QQ
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.weibo
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.skill
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.interest
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.lang
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.avatar_file
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String avatarFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.area_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.street
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.zip
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_partner.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

    public Partner() {
	}

	public Partner(Long id) {
		this.id = id;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.id
     *
     * @return the value of tb_partner.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.id
     *
     * @param id the value for tb_partner.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.active
     *
     * @return the value of tb_partner.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.active
     *
     * @param active the value for tb_partner.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.type
     *
     * @return the value of tb_partner.type
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.type
     *
     * @param type the value for tb_partner.type
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.name
     *
     * @return the value of tb_partner.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.name
     *
     * @param name the value for tb_partner.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.comment
     *
     * @return the value of tb_partner.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.comment
     *
     * @param comment the value for tb_partner.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.gender
     *
     * @return the value of tb_partner.gender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.gender
     *
     * @param gender the value for tb_partner.gender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.hometown
     *
     * @return the value of tb_partner.hometown
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.hometown
     *
     * @param hometown the value for tb_partner.hometown
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setHometown(String hometown) {
        this.hometown = hometown == null ? null : hometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.trade_id
     *
     * @return the value of tb_partner.trade_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.trade_id
     *
     * @param tradeId the value for tb_partner.trade_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.function
     *
     * @return the value of tb_partner.function
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.function
     *
     * @param function the value for tb_partner.function
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.birthday
     *
     * @return the value of tb_partner.birthday
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.birthday
     *
     * @param birthday the value for tb_partner.birthday
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.signature
     *
     * @return the value of tb_partner.signature
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.signature
     *
     * @param signature the value for tb_partner.signature
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.email
     *
     * @return the value of tb_partner.email
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.email
     *
     * @param email the value for tb_partner.email
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.mobile
     *
     * @return the value of tb_partner.mobile
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.mobile
     *
     * @param mobile the value for tb_partner.mobile
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.phone
     *
     * @return the value of tb_partner.phone
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.phone
     *
     * @param phone the value for tb_partner.phone
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.QQ
     *
     * @return the value of tb_partner.QQ
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.QQ
     *
     * @param qq the value for tb_partner.QQ
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.weibo
     *
     * @return the value of tb_partner.weibo
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.weibo
     *
     * @param weibo the value for tb_partner.weibo
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.skill
     *
     * @return the value of tb_partner.skill
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.skill
     *
     * @param skill the value for tb_partner.skill
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.interest
     *
     * @return the value of tb_partner.interest
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.interest
     *
     * @param interest the value for tb_partner.interest
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setInterest(String interest) {
        this.interest = interest == null ? null : interest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.lang
     *
     * @return the value of tb_partner.lang
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.lang
     *
     * @param lang the value for tb_partner.lang
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.avatar_file
     *
     * @return the value of tb_partner.avatar_file
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getAvatarFile() {
        return avatarFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.avatar_file
     *
     * @param avatarFile the value for tb_partner.avatar_file
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setAvatarFile(String avatarFile) {
        this.avatarFile = avatarFile == null ? null : avatarFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.area_id
     *
     * @return the value of tb_partner.area_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.area_id
     *
     * @param areaId the value for tb_partner.area_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.street
     *
     * @return the value of tb_partner.street
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.street
     *
     * @param street the value for tb_partner.street
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.zip
     *
     * @return the value of tb_partner.zip
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.zip
     *
     * @param zip the value for tb_partner.zip
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.company_id
     *
     * @return the value of tb_partner.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.company_id
     *
     * @param companyId the value for tb_partner.company_id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.create_uid
     *
     * @return the value of tb_partner.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.create_uid
     *
     * @param createUid the value for tb_partner.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.write_uid
     *
     * @return the value of tb_partner.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.write_uid
     *
     * @param writeUid the value for tb_partner.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteUid(Long writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.create_date
     *
     * @return the value of tb_partner.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.create_date
     *
     * @param createDate the value for tb_partner.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_partner.write_date
     *
     * @return the value of tb_partner.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_partner.write_date
     *
     * @param writeDate the value for tb_partner.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

	@Override
	public String toString() {
		return "Partner [id=" + id + ", active=" + active + ", type=" + type + ", name=" + name + ", comment=" + comment
				+ ", gender=" + gender + ", hometown=" + hometown + ", tradeId=" + tradeId + ", function=" + function
				+ ", birthday=" + birthday + ", signature=" + signature + ", email=" + email + ", mobile=" + mobile
				+ ", phone=" + phone + ", qq=" + qq + ", weibo=" + weibo + ", skill=" + skill + ", interest=" + interest
				+ ", lang=" + lang + ", avatarFile=" + avatarFile + ", areaId=" + areaId + ", street=" + street
				+ ", zip=" + zip + ", companyId=" + companyId + ", createUid=" + createUid + ", writeUid=" + writeUid
				+ ", createDate=" + createDate + ", writeDate=" + writeDate + "]";
	}
}