package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_private_lettle")
public class PrivateLettle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.details
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.sender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.receiver
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.read
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_private_lettle.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.id
     *
     * @return the value of tb_private_lettle.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.id
     *
     * @param id the value for tb_private_lettle.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.active
     *
     * @return the value of tb_private_lettle.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.active
     *
     * @param active the value for tb_private_lettle.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.details
     *
     * @return the value of tb_private_lettle.details
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.details
     *
     * @param details the value for tb_private_lettle.details
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.sender
     *
     * @return the value of tb_private_lettle.sender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.sender
     *
     * @param sender the value for tb_private_lettle.sender
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setSender(Long sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.receiver
     *
     * @return the value of tb_private_lettle.receiver
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.receiver
     *
     * @param receiver the value for tb_private_lettle.receiver
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.read
     *
     * @return the value of tb_private_lettle.read
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.read
     *
     * @param read the value for tb_private_lettle.read
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setRead(String read) {
        this.read = read == null ? null : read.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.create_uid
     *
     * @return the value of tb_private_lettle.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.create_uid
     *
     * @param createUid the value for tb_private_lettle.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.write_uid
     *
     * @return the value of tb_private_lettle.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.write_uid
     *
     * @param writeUid the value for tb_private_lettle.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteUid(Long writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.create_date
     *
     * @return the value of tb_private_lettle.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.create_date
     *
     * @param createDate the value for tb_private_lettle.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_private_lettle.write_date
     *
     * @return the value of tb_private_lettle.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_private_lettle.write_date
     *
     * @param writeDate the value for tb_private_lettle.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
}