package com.radacat.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;

@Entity
@Table(name="tb_product")
public class Product implements Serializable{
    
	/**
	 * serialVersionUID
	 * long
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.id
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.active
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.stop
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String stop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.name
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.price
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.market_price
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.cost_price
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.length
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.width
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.height
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.uom
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String uom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.image_url
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.comment
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.weight
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.type
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.color
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.attribute
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.supplier
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.keyword
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.place_origin
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private String placeOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.start_time
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.end_time
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.create_uid
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.write_uid
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.create_date
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.write_date
     *
     * @mbggenerated Mon May 01 01:46:17 CST 2017
     */
	@Column
    private Date writeDate;

	public Product() {
	}
	
	public Product(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getActive() {
		return active;
	}


	public void setActive(String active) {
		this.active = active;
	}


	public String getStop() {
		return stop;
	}


	public void setStop(String stop) {
		this.stop = stop;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Double getPrice() {
		return price;
	}


	public void setPrice(Double price) {
		this.price = price;
	}


	public Double getMarketPrice() {
		return marketPrice;
	}


	public void setMarketPrice(Double marketPrice) {
		this.marketPrice = marketPrice;
	}


	public Double getCostPrice() {
		return costPrice;
	}


	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}


	public Double getLength() {
		return length;
	}


	public void setLength(Double length) {
		this.length = length;
	}


	public Double getWidth() {
		return width;
	}


	public void setWidth(Double width) {
		this.width = width;
	}


	public Double getHeight() {
		return height;
	}


	public void setHeight(Double height) {
		this.height = height;
	}


	public String getUom() {
		return uom;
	}


	public void setUom(String uom) {
		this.uom = uom;
	}


	public String getImageUrl() {
		return imageUrl;
	}


	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}


	public String getComment() {
		return comment;
	}


	public void setComment(String comment) {
		this.comment = comment;
	}


	public Double getWeight() {
		return weight;
	}


	public void setWeight(Double weight) {
		this.weight = weight;
	}


	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}


	public String getColor() {
		return color;
	}


	public void setColor(String color) {
		this.color = color;
	}


	public String getAttribute() {
		return attribute;
	}


	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}


	public String getSupplier() {
		return supplier;
	}


	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}


	public String getKeyword() {
		return keyword;
	}


	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}


	public String getPlaceOrigin() {
		return placeOrigin;
	}


	public void setPlaceOrigin(String placeOrigin) {
		this.placeOrigin = placeOrigin;
	}


	public Date getStartTime() {
		return startTime;
	}


	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}


	public Date getEndTime() {
		return endTime;
	}


	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}


	public Long getCreateUid() {
		return createUid;
	}


	public void setCreateUid(Long createUid) {
		this.createUid = createUid;
	}


	public Long getWriteUid() {
		return writeUid;
	}


	public void setWriteUid(Long writeUid) {
		this.writeUid = writeUid;
	}


	public Date getCreateDate() {
		return createDate;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public Date getWriteDate() {
		return writeDate;
	}


	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}


	@Override
	public String toString() {
		return "Product [id=" + id + ", active=" + active + ", stop=" + stop + ", name=" + name + ", price=" + price
				+ ", marketPrice=" + marketPrice + ", costPrice=" + costPrice + ", length=" + length + ", width="
				+ width + ", height=" + height + ", uom=" + uom + ", imageUrl=" + imageUrl + ", comment=" + comment
				+ ", weight=" + weight + ", type=" + type + ", color=" + color + ", attribute=" + attribute
				+ ", supplier=" + supplier + ", keyword=" + keyword + ", placeOrigin=" + placeOrigin + ", startTime="
				+ startTime + ", endTime=" + endTime + ", createUid=" + createUid + ", writeUid=" + writeUid
				+ ", createDate=" + createDate + ", writeDate=" + writeDate + "]";
	}
}