package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_role")
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Long writeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;
	
	public Role() {
		super();
	}

    public Role(Integer id) {
		super();
		this.id = id;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.id
     *
     * @return the value of tb_role.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	
	
    public Integer getId() {
        return id;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.id
     *
     * @param id the value for tb_role.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.active
     *
     * @return the value of tb_role.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.active
     *
     * @param active the value for tb_role.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.name
     *
     * @return the value of tb_role.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.name
     *
     * @param name the value for tb_role.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.comment
     *
     * @return the value of tb_role.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.comment
     *
     * @param comment the value for tb_role.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_uid
     *
     * @return the value of tb_role.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_uid
     *
     * @param createUid the value for tb_role.create_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.write_uid
     *
     * @return the value of tb_role.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.write_uid
     *
     * @param writeUid the value for tb_role.write_uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteUid(Long writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_date
     *
     * @return the value of tb_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_date
     *
     * @param createDate the value for tb_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.write_date
     *
     * @return the value of tb_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.write_date
     *
     * @param writeDate the value for tb_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

	@Override
	public String toString() {
		return "Role [id=" + id + ", active=" + active + ", name=" + name + ", comment=" + comment + ", createUid="
				+ createUid + ", writeUid=" + writeUid + ", createDate=" + createDate + ", writeDate=" + writeDate
				+ "]";
	}
}