package com.radacat.domain;

public class RolePermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_permission.pid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_permission.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_permission.pid
     *
     * @return the value of tb_role_permission.pid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_permission.pid
     *
     * @param pid the value for tb_role_permission.pid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_permission.rid
     *
     * @return the value of tb_role_permission.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_permission.rid
     *
     * @param rid the value for tb_role_permission.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}