package com.radacat.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_stage")
public class Stage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stage.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stage.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stage.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stage.id
     *
     * @return the value of tb_stage.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stage.id
     *
     * @param id the value for tb_stage.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stage.active
     *
     * @return the value of tb_stage.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stage.active
     *
     * @param active the value for tb_stage.active
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stage.name
     *
     * @return the value of tb_stage.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stage.name
     *
     * @param name the value for tb_stage.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}