package com.radacat.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="tb_trade")
public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.code
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.pcode
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
	@Column
    private Date writeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.vision
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Byte vision;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.id
     *
     * @return the value of tb_trade.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.id
     *
     * @param id the value for tb_trade.id
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.code
     *
     * @return the value of tb_trade.code
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.code
     *
     * @param code the value for tb_trade.code
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.name
     *
     * @return the value of tb_trade.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.name
     *
     * @param name the value for tb_trade.name
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.comment
     *
     * @return the value of tb_trade.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.comment
     *
     * @param comment the value for tb_trade.comment
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.pcode
     *
     * @return the value of tb_trade.pcode
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.pcode
     *
     * @param pcode the value for tb_trade.pcode
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.create_date
     *
     * @return the value of tb_trade.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.create_date
     *
     * @param createDate the value for tb_trade.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.write_date
     *
     * @return the value of tb_trade.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.write_date
     *
     * @param writeDate the value for tb_trade.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.vision
     *
     * @return the value of tb_trade.vision
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Byte getVision() {
        return vision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.vision
     *
     * @param vision the value for tb_trade.vision
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setVision(Byte vision) {
        this.vision = vision;
    }
}