package com.radacat.domain;

import java.util.Date;

public class UploadFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.id
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.owner_uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Long ownerUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.suffix_name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private String suffixName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.type
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.last_modified_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.size
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Double size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.url
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.create_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.write_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    private Date writeDate;

    
    public UploadFile() {
	}

	public UploadFile(Integer uid, String name, String type, Date lastModifiedDate, Double size) {
		super();
		this.uid = uid;
		this.name = name;
		this.type = type;
		this.lastModifiedDate = lastModifiedDate;
		this.size = size;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.id
     *
     * @return the value of tb_file.id
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.id
     *
     * @param id the value for tb_file.id
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.uid
     *
     * @return the value of tb_file.uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.uid
     *
     * @param uid the value for tb_file.uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.owner_uid
     *
     * @return the value of tb_file.owner_uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Long getOwnerUid() {
        return ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.owner_uid
     *
     * @param ownerUid the value for tb_file.owner_uid
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setOwnerUid(Long ownerUid) {
        this.ownerUid = ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.name
     *
     * @return the value of tb_file.name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.name
     *
     * @param name the value for tb_file.name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.suffix_name
     *
     * @return the value of tb_file.suffix_name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public String getSuffixName() {
        return suffixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.suffix_name
     *
     * @param suffixName the value for tb_file.suffix_name
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setSuffixName(String suffixName) {
        this.suffixName = suffixName == null ? null : suffixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.type
     *
     * @return the value of tb_file.type
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.type
     *
     * @param type the value for tb_file.type
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.last_modified_date
     *
     * @return the value of tb_file.last_modified_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.last_modified_date
     *
     * @param lastModifiedDate the value for tb_file.last_modified_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.size
     *
     * @return the value of tb_file.size
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.size
     *
     * @param size the value for tb_file.size
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.url
     *
     * @return the value of tb_file.url
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.url
     *
     * @param url the value for tb_file.url
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.create_date
     *
     * @return the value of tb_file.create_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.create_date
     *
     * @param createDate the value for tb_file.create_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.write_date
     *
     * @return the value of tb_file.write_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.write_date
     *
     * @param writeDate the value for tb_file.write_date
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
}