package com.radacat.domain;

import java.util.Date;

public class UserRole extends UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Date writeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.create_date
     *
     * @return the value of tb_user_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.create_date
     *
     * @param createDate the value for tb_user_role.create_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.write_date
     *
     * @return the value of tb_user_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.write_date
     *
     * @param writeDate the value for tb_user_role.write_date
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
}