package com.radacat.domain;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.rid
     *
     * @return the value of tb_user_role.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.rid
     *
     * @param rid the value for tb_user_role.rid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.uid
     *
     * @return the value of tb_user_role.uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.uid
     *
     * @param uid the value for tb_user_role.uid
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}