package com.radacat.mapper;

import com.radacat.domain.Agency;

public interface AgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Agency selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agency
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Agency record);
}