package com.radacat.mapper;

import com.radacat.domain.Country;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_country
     *
     * @mbggenerated Thu May 04 19:47:19 CST 2017
     */
    int updateByPrimaryKey(Country record);
}