package com.radacat.mapper;

import com.radacat.domain.Depart;

public interface DepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Depart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_depart
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Depart record);
}