package com.radacat.mapper;

import com.radacat.domain.HistoryPoint;

public interface HistoryPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(HistoryPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(HistoryPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    HistoryPoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(HistoryPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_point
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(HistoryPoint record);
}