package com.radacat.mapper;

import com.radacat.domain.Linkman;

public interface LinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Linkman selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_linkman
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Linkman record);
}