package com.radacat.mapper;

import com.radacat.domain.Opportunity;

public interface OpportunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Opportunity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_opportunity
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Opportunity record);
}