package com.radacat.mapper;

import java.util.List;

import com.radacat.domain.Partner;

public interface PartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Partner partner);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Partner partner);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Partner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Partner partner);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_partner
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Partner partner);
    
//    @Select("select * from tb_partner where active='t' and type='1'")
    List<Partner> findAllAdmin();
    
//    @Select("select * from tb_partner where active='t' and type='3'")
    List<Partner> findAllPartner();
}