package com.radacat.mapper;

import com.radacat.domain.Points;

public interface PointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Points selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Points record);
}