package com.radacat.mapper;

import com.radacat.domain.PrivateLettle;

public interface PrivateLettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(PrivateLettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(PrivateLettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    PrivateLettle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(PrivateLettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_private_lettle
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(PrivateLettle record);
}