package com.radacat.mapper;

import com.radacat.domain.RolePermissionKey;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_permission
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_permission
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_permission
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(RolePermissionKey record);
}