package com.radacat.mapper;

import com.radacat.domain.Stage;

public interface StageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    Stage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stage
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(Stage record);
}