package com.radacat.mapper;

import com.radacat.domain.UploadFile;

public interface UploadFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    int insert(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    int insertSelective(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    UploadFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    int updateByPrimaryKeySelective(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbggenerated Sat Apr 29 23:29:55 CST 2017
     */
    int updateByPrimaryKey(UploadFile uploadFile);
}