package com.radacat.mapper;

import com.radacat.domain.UserLog;

public interface UserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    UserLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(UserLog record);
}