package com.radacat.mapper;

import com.radacat.domain.UserPoints;

public interface UserPointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insert(UserPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int insertSelective(UserPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    UserPoints selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKeySelective(UserPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_points
     *
     * @mbggenerated Sat Apr 15 12:44:39 CST 2017
     */
    int updateByPrimaryKey(UserPoints record);
}